package dev.darkblade.langmanager.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import org.yaml.snakeyaml.Yaml;
import java.io.InputStream;
import java.util.Map;
import java.util.Properties;
import java.util.LinkedHashMap;

public abstract class GenerateMessageKeysTask extends DefaultTask {

    @Input
    public abstract Property<String> getNamespace();

    @Input
    public abstract Property<String> getSourceFile();

    @Input
    public abstract Property<String> getTargetPackage();

    @Input
    public abstract Property<String> getClassName();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @TaskAction
    public void generate() throws Exception {
        String ns = getNamespace().get();
        String pkg = getTargetPackage().get();
        String cls = getClassName().get();
        
        File srcFile = getProject().file(getSourceFile().get());
        if (!srcFile.exists()) {
            getLogger().warn("Source file for message keys not found: {}", srcFile.getAbsolutePath());
            return;
        }

        Properties props = new Properties();
        try (FileInputStream fis = new FileInputStream(srcFile)) {
            if (srcFile.getName().endsWith(".yml") || srcFile.getName().endsWith(".yaml")) {
                Yaml yaml = new Yaml();
                Map<String, Object> yamlMap = yaml.load(fis);
                if (yamlMap != null) {
                    flattenYaml(yamlMap, "", props);
                }
            } else {
                props.load(fis);
            }
        }

        File outDir = getOutputDirectory().get().dir(pkg.replace('.', '/')).getAsFile();
        if (!outDir.exists() && !outDir.mkdirs()) {
            throw new RuntimeException("Could not create output directory: " + outDir);
        }

        File outFile = new File(outDir, cls + ".java");
        try (PrintWriter writer = new PrintWriter(new FileWriter(outFile))) {
            writer.println("package " + pkg + ";");
            writer.println();
            writer.println("import dev.darkblade.langmanager.api.MessageKey;");
            writer.println();
            writer.println("/**");
            writer.println(" * Auto-generated by LangManager Gradle Plugin.");
            writer.println(" */");
            writer.println("public enum " + cls + " implements MessageKey {");
            
            boolean first = true;
            for (String key : props.stringPropertyNames()) {
                if (!first) {
                    writer.println(",");
                }
                first = false;
                
                String enumName = key.toUpperCase().replace('.', '_').replace('-', '_');
                writer.print("    " + enumName + "(\"" + ns + "\", \"" + key + "\")");
            }
            if (!first) {
                writer.println(";");
            } else {
                writer.println("; // No keys found");
            }
            
            writer.println();
            writer.println("    private final String namespace;");
            writer.println("    private final String path;");
            writer.println();
            writer.println("    " + cls + "(String namespace, String path) {");
            writer.println("        this.namespace = namespace;");
            writer.println("        this.path = path;");
            writer.println("    }");
            writer.println();
            writer.println("    @Override");
            writer.println("    public String namespace() {");
            writer.println("        return namespace;");
            writer.println("    }");
            writer.println();
            writer.println("    @Override");
            writer.println("    public String path() {");
            writer.println("        return path;");
            writer.println("    }");
            writer.println("}");
        }
        
        getLogger().info("Generated {} message keys into {}.{}", props.size(), pkg, cls);
    }

    @SuppressWarnings("unchecked")
    private void flattenYaml(Map<String, Object> source, String path, Properties dest) {
        for (Map.Entry<String, Object> entry : source.entrySet()) {
            String key = entry.getKey();
            String newPath = path.isEmpty() ? key : path + "." + key;
            Object value = entry.getValue();
            if (value instanceof Map) {
                flattenYaml((Map<String, Object>) value, newPath, dest);
            } else if (value != null) {
                dest.setProperty(newPath, String.valueOf(value));
            }
        }
    }
}
